version: '3.8'
services:
  web:
    build: .
    restart: always
    ports:
      - "${HOST_PORT:-9064}:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - violation-record-data:/var/lib/postgresql/data

volumes:
  violation-record-data:
    name: violation-record-data
    external: true